spring.application.name=kinalapp

#Conexion a MySql
spring.datasource.url=jdbc:mysql://localhost:3306/dbClientes_in5am?createDatabaseIfNotExist=true
spring.datasource.username= IN5AM
spring.datasource.password= _odmon5Am

#JPA/ Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9000
